export const INCREMENT_CART_COUNT = "INCREMENT_CART_COUNT";
export const DECREMENT_CART_COUNT = "DECREMENT_CART_COUNT";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
